### ISSUE TITLE
Missing modules for linux-surface debian kernell

### ISSUE THREAD

**Issue by kisisten** [linux-surface/linux-surface#144]
If the linux-surface debian repository kernels are based on the Debian release config, why am I missing these two modules which are there on stock kernels?

$ sudo modprobe ashmem_linux
$ sudo modprobe binder_linux

Thanks,
A.

**Comment by archseer** [comment]
We ended up basing them on the Ubuntu configs instead I think. The Debian ones were such a pain to get building. We spent about two weeks trying to hack around their tooling to fit our usecase, but the even bigger problem was that new minor releases weren't always tagged or publicly published on time.

Since none of us are Debian/Ubuntu users we settled on using Ubuntu configs, but if someone was to go and switch to proper debian configs we would accept this change.

**Comment by qzed** [comment]
Are those modules really upstream modules? As far as I can tell those are external (https://github.com/anbox/anbox-modules), so you need to install them, preferably via a dkms package. Seems like there is one for Ubuntu, should probably also work on Debian: https://docs.anbox.io/userguide/install_kernel_modules.html.

**Comment by kisisten** [comment]
> Are those modules really upstream modules? As far as I can tell those are external (https://github.com/anbox/anbox-modules), so you need to install them, preferably via a dkms package. Seems like there is one for Ubuntu, should probably also work on Debian: https://docs.anbox.io/userguide/install_kernel_modules.html.

Yes, the Debian kernel has them in /lib/modules/$kernel_version/kernel/drivers/android/binder_linux.ko and /usr/lib/modules/$kernel_version/kernel/drivers/staging/android/ashmem_linux.ko

**Comment by archseer** [comment]
@qzed Debian seems to have them enabled, on your link it says:

> Debian has enabled these modules since kernel 4.17.3. So you don’t need to bother how to install. Currently kernel 4.17.3 and above are only available in Debian Unstable.

**Comment by qzed** [comment]
Ah I missed that, sorry. It also states that they should be enabled on Ubuntu 19.04 and later... however they're not enabled on the kernel-ppa. It looks like we should consider adding
```
CONFIG_ASHMEM=m
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=m
CONFIG_ANDROID_BINDERFS=m
CONFIG_ANDROID_BINDER_DEVICES=""
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set
```
to https://github.com/linux-surface/linux-surface/blob/master/pkg/debian/ubuntu.config (at least according to the config of some Ubuntu 5.4 kernel package). 

Can someone confirm that those are correct and we're not missing anything else?

**Comment by kisisten** [comment]
This is what I have in Debian stable with backports  (config-5.4.0-0.bpo.4-amd64)

CONFIG_ASHMEM=m
# CONFIG_ANDROID_VSOC is not set
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=m
# CONFIG_ANDROID_BINDERFS is not set
CONFIG_ANDROID_BINDER_DEVICES="binder"
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set

And this is for debian stable config-4.19.0-8-amd64 default kernel:

CONFIG_ASHMEM=m
# CONFIG_ANDROID_VSOC is not set
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=m
CONFIG_ANDROID_BINDER_DEVICES="binder"
# CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set

**Comment by kisisten** [comment]
This is what I have in Debian stable with backports (config-5.4.0-0.bpo.4-amd64)

 CONFIG_ASHMEM=m
 #CONFIG_ANDROID_VSOC is not set
 CONFIG_ANDROID=y
 CONFIG_ANDROID_BINDER_IPC=m
 #CONFIG_ANDROID_BINDERFS is not set
 CONFIG_ANDROID_BINDER_DEVICES="binder"
 #CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set

And this is for Debian stable config-4.19.0-8-amd64 default kernel:

 CONFIG_ASHMEM=m
 #CONFIG_ANDROID_VSOC is not set
 CONFIG_ANDROID=y
 CONFIG_ANDROID_BINDER_IPC=m
 CONFIG_ANDROID_BINDER_DEVICES="binder"
 #CONFIG_ANDROID_BINDER_IPC_SELFTEST is not set

**Comment by qzed** [comment]
Should be fixed with https://github.com/linux-surface/linux-surface/commit/1d42263e98b668f4c7246d201cec23a100af3a73. New kernels are currently building.

**Comment by kisisten** [comment]
The modules are still missing and so are the drivers to build the dkms modules 
/usr/lib/modules/$(uname -r)/kernel/drivers/staging/android/ashmem_linux.ko

**Comment by qzed** [comment]
I've pretty much set the options above in https://github.com/linux-surface/linux-surface/blob/master/pkg/debian/kernel/ubuntu.config. Can you check if there have been any updates to those on the stock Debian kernels? Any idea if there might be any option missing?

**Comment by qzed** [comment]
So it seems like the [upstream](https://github.com/torvalds/linux/blob/v5.7/drivers/staging/android/ashmem.c) `ashmem` source doesn't allow for it to be built as module (`m`) and only allows it to be built-in (`y`). There is an additional patch (which has not been applied to the PPA we're using as source for some reason) which changes the option from `bool` to `tristate`, thus effectively allowing `ashmem` and `binder` to be built as modules.

As a note: The module doesn't have a `module_exit` function, meaning that it's not possible to unload it (without using the `-f` option for `rmmod`, which isn't really a good idea here due to the missing clean-up). On the other hand, that means that there's no problem with the missing cleanup, as it (normally) can't be unloaded, so the patches should be safe to add.

Will have a go at that later.

The patches in question:
- [`android-enable-building-ashmem-and-binder-as-modules.patch`](https://salsa.debian.org/kernel-team/linux/-/blob/7f99deaf5bf62297716de4c2007c50a20397cf30/debian/patches/debian/android-enable-building-ashmem-and-binder-as-modules.patch)
- [`export-symbols-needed-by-android-drivers.patch`](https://salsa.debian.org/kernel-team/linux/-/blob/7f99deaf5bf62297716de4c2007c50a20397cf30/debian/patches/debian/export-symbols-needed-by-android-drivers.patch)

**Comment by qzed** [comment]
Alright, patches have been added, new kernels are building. Hopefully it'll work this time.

**Comment by qzed** [comment]
I assume that this works now as there haven't been any complaints. Please let me know if there are any issues.

**Comment by afalout** [comment]
Hello all,

On Ubuntu Groovy this modules are still missing with current kernel (5.10.16-surface)

ls -1 /dev/{ashmem,binder}
ls: cannot access '/dev/ashmem': No such file or directory
ls: cannot access '/dev/binder': No such file or directory

Therefore, Anbox cannot be installed. https://docs.anbox.io/userguide/install_kernel_modules.html states:

"Starting with Ubuntu 19.04 binder and ashmem are now build with the standard Ubuntu kernel (>= 5.0) and you don’t have to install the modules from the PPA anymore."

Is there anything I can do to fix this, or can someone please check the build configuration?

Thanks,
Andrej

**Comment by qzed** [comment]
As far as I can tell the modules are present and config options should be set. Did you try to load the modules before running the `ls` (i.e. run `modprobe ashmem_linux` and `modprobe binder_linux`)?

**Comment by afalout** [comment]
Thanks for the response. You are right, modules are there and load, I just followed the Anbox install guide a bit too literally - eg ls -1 /dev/{ashmem,binder} assuming they will be already loaded if they exist...
Apologies for that.
Andrej

**Comment by qzed** [comment]
No worries.

**Comment by Sparticuz** [comment]
@qzed Can you add Ashmem and binder to the Arch kernel as well?

**Comment by qzed** [comment]
Ah, looks like those are supposed to be enabled in-kernel now instead of installing via an external DKMS module. Should be enabled in the next release (commit b6c16eb4e551d7619cf63b34a9c57e05002f6386).

**Comment by Sparticuz** [comment]
> Ah, looks like those are supposed to be enabled in-kernel now instead of installing via an external DKMS module. Should be enabled in the next release (commit [b6c16eb](https://github.com/linux-surface/linux-surface/commit/b6c16eb4e551d7619cf63b34a9c57e05002f6386)).
> 
> Let me know if that didn't work.

https://github.com/linux-surface/linux-surface/blob/b6c16eb4e551d7619cf63b34a9c57e05002f6386/pkg/arch/kernel/arch.config#L24 says ANRDOID. I think the Arch kernel might have failed, not seeing 5.13.13-1 on my system.

**Comment by qzed** [comment]
> https://github.com/linux-surface/linux-surface/blob/b6c16eb4e551d7619cf63b34a9c57e05002f6386/pkg/arch/kernel/arch.config#L24
> says ANRDOID. I think the Arch kernel might have failed, not seeing 5.13.13-1 on my system.

Oh right, thanks for spotting this. The kernel did build but the repo hasn't been updated yet. Config is wrong though due to the typo, but I've fixed that now and the next release is building.
 
> EDIT: Also, does it need `CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"`. Trying to run Anbox.

I've taken the config stuff from https://wiki.archlinux.org/title/Anbox#Using_binderfs. As far as I can tell this should be the "new" way, so I'd hope that works as well.

**Comment by qzed** [comment]
Okay, new kernel is built and I've triggered a repo update. Unfortunately it looks like `CONFIG_ASHMEM` hasn't been enabled. Turns out `CONFIG_ASHMEM` is a bool type and doesn't accept `m` (only `n` and `y`). So I guess the Arch Wiki is out-of-date.

The Arch `-zen` kernel has `CONFIG_ASHMEM=y`, so I guess that should work then. Next build is running... hopefully it works this time.

**Comment by Sparticuz** [comment]
> Okay, new kernel is built and I've triggered a repo update. Unfortunately it looks like `CONFIG_ASHMEM` hasn't been enabled. Turns out `CONFIG_ASHMEM` is a bool type and doesn't accept `m` (only `n` and `y`). So I guess the Arch Wiki is out-of-date.
> 
> The Arch `-zen` kernel has `CONFIG_ASHMEM=y`, so I guess that should work then. Next build is running... hopefully it works this time.

Yeah I just tried to `modprobe`, but got module not found for `ashmem-linux`. If it's `y`, I don't need to do that, right?

**Comment by qzed** [comment]
> Yeah I just tried to `modprobe`, but got module not found for `ashmem-linux`. If it's `y`, I don't need to do that, right?

Right, you only need to load `binder-linux`.

v5.13.13-3 should be available in a couple of minutes (as soon as the server pulls in the new repo data).

**Comment by Sparticuz** [comment]
> > Yeah I just tried to `modprobe`, but got module not found for `ashmem-linux`. If it's `y`, I don't need to do that, right?
> 
> Right, you only need to load `binder-linux`.

I also get `binder-linux` not found in `/lib/modules/.....`, but I think the config is setting up `binderfs`, not `binder` (https://wiki.archlinux.org/title/Anbox#Mounting_binderfs)

**Comment by qzed** [comment]
Ah yeah, that might be right.

**Comment by qzed** [comment]
So according to the kernel config, all necessary options should be set now.

**Comment by Sparticuz** [comment]
> Okay, new kernel is built and I've triggered a repo update. Unfortunately it looks like `CONFIG_ASHMEM` hasn't been enabled. Turns out `CONFIG_ASHMEM` is a bool type and doesn't accept `m` (only `n` and `y`). So I guess the Arch Wiki is out-of-date.
> 
> The Arch `-zen` kernel has `CONFIG_ASHMEM=y`, so I guess that should work then. Next build is running... hopefully it works this time.

`ashmem-linux` is loaded in -3.

**Comment by qzed** [comment]
I assume Anbox works then?

**Comment by Sparticuz** [comment]
> I assume Anbox works then?

I'm still working on trying to figure it out. Having some difficulty building anbox, plus there is another project, waydroid, that is kind of in the middle of migrating some things around. That being said, ashmem and binderfs are both showing in /dev, so I'm assuming they are all good.

**Comment by qzed** [comment]
Thanks for the feedback, let me know if there's any issue with the kernel.

**Comment by j4ckgrey** [comment]
> Thanks for the feedback, let me know if there's any issue with the kernel.

Hi there, i got binder enabled but not ashmem. Any idea?

**Comment by NP-chaonay** [comment]
> > Thanks for the feedback, let me know if there's any issue with the kernel.
> 
> Hi there, i got binder enabled but not ashmem. Any idea? modprobe ashmem_linux modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/5.18.1-surface

easy explain: that module is not installed for kernel name "5.18.1-surface", how you install, sudo make install or dkms or something.
detailed:
- if module come from dkms or something dynamically build (from .o/.c file); check if it already installed to the build system and check if build system have build them into module installation dir of that kernel name (maybe at /lib/modules/<kernel name>/kernel)
- if manually copy module file, check if file is existed and in .ko file
- if manually-built kernel, check if build system of kernel source make the wanted file. is anything wrong.

**Comment by qzed** [comment]
@j4ckgrey see https://github.com/linux-surface/linux-surface/issues/96#issuecomment-1146649661 and https://github.com/anbox/anbox/issues/2042. `ashmem` was removed upstream, so it's no longer included in the kernel. You'll need to look for alternatives, such as building/installing it as external module.
