### ISSUE TITLE
Latest 6.12.3 headers missing .config file

### ISSUE THREAD

**Issue by junalmeida** [linux-surface/linux-surface#1654]
When trying to install kernel driver using dkms, I get the following message: 
Kernel config /lib/modules/6.12.3-surface-2/build/.config not found, modules won't be signed

And indeed the file is missing and driver won´t be signed. 

### Environment

- Hardware model:  Surface Book 2
- Kernel version: Linux marcos-surfacebook2 6.12.3-surface-2 #2 SMP PREEMPT_DYNAMIC Thu Dec 12 00:45:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Distribution: KDE Neon / Ubuntu Noble

**Comment by der-siebte-schatten** [comment]
I have a similar issue on my Surface Book 3, LMDE 6.
I cannot start VMWare Workstation, as it doesn't find the 6.12.3 headers, because this file is missing. Therefore I cannot compile the VMWare kernel.

Reinstalling the package with Synaptic did not solve the issue, the file is missing altogether.

**Comment by davidbitterlich** [comment]
Hi, thank you for that hint with the missing .config file in the kernel headers directory. I was able to build vmware kernel modules successfully after I copied the older .config file from the linux-headers-6.10.10-surface-1 header's directory.

So if someone else has this problem (and still has the old kernel and headers on the system), try this

**Comment by ocean1ee1** [comment]
I just found there ​were something changed in ./scripts/package/install-extmod-build file in kernel source codes - the copy .config file to ${destdir}  command was removed.

Also I tried to add this copy command back, build the kernel and install deb package in ubuntu 24.04, this error [.config not found] will be gone. 

If someone want to try the latest kernel, you can try to add copy .config back

@qzed just FYI, hope you don't mind

**Comment by qzed** [comment]
@ocean1ee1 Thanks for tracking this down!

I guess we can patch that back in, we're already adding some debian/ubuntu specific patches to the packaging side anyway. I'll have a look at it when I have a bit more time than now, unfortunately I'm a bit swamped again.

**Comment by qzed** [comment]
Should be fixed with the next release (v6.13.6). It's building now.

**Comment by der-siebte-schatten** [comment]
I confirm fixed with 6.13.6 on LMDE 6. VMWare Workstation is building fine.

**Comment by StatusCode404** [comment]
I just reopened a bug very similar in Virtualbox's bugtracker a few days ago.  Are you saying @qzed that it is fixed in linux kernel v6.13.6+ ?  https://www.virtualbox.org/ticket/20425

Hopefully it gets ported to 6.12 LTS if so...

**Comment by qzed** [comment]
@StatusCode404 unfortunately it's not fixed upstream. I've just added a patch to revert the upstream change on our side: https://github.com/linux-surface/linux-surface/blob/0e17ba8007708620dd759cab3f107ea033514c43/pkg/debian/kernel/0001-kbuild-Copy-config-to-target-directory.patch

**Comment by StatusCode404** [comment]
Has anyone reported it upstream?
Unfortunately I don't know how to report this upstream.  I haven't really looked or have had the need to.  Could someone here kindly do it if they know how to do it?

**Comment by ocean1ee1** [comment]
Since I also don't know the process, I just sent a mail to Masahiro Yamada who committed [the remove command](https://web.git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/scripts/package/install-extmod-build?h=v6.13.7&id=aaed5c7739be81ebdd6008aedc8befd98c88e67a), however I don't get a response.

Actually not sure where should be reported to, for me to distribution - ubuntu?  or to bugzilla.kernel.org ?

**Comment by qzed** [comment]
Generally try distro first. After that, it depends on the subsystem: Either mailing list or kernel bugzilla. But generally the author of that patch should be able to help out.

**Comment by StatusCode404** [comment]
> Since I also don't know the process, I just sent a mail to Masahiro Yamada who committed [the remove command](https://web.git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/scripts/package/install-extmod-build?h=v6.13.7&id=aaed5c7739be81ebdd6008aedc8befd98c88e67a), however I don't get a response.
> 
> Actually not sure where should be reported to, for me to distribution - ubuntu? or to bugzilla.kernel.org ?

Perhaps quote that Virtualbox bug link I pasted above to Masahiro?
Also if you have one with VMware?

It gives more weight that it is something real rather than random noise requests he probably gets from everyone?

**Comment by jortle** [comment]
> [@StatusCode404](https://github.com/StatusCode404) unfortunately it's not fixed upstream. I've just added a patch to revert the upstream change on our side: https://github.com/linux-surface/linux-surface/blob/0e17ba8007708620dd759cab3f107ea033514c43/pkg/debian/kernel/0001-kbuild-Copy-config-to-target-directory.patch

how can I use the patch? every time I try to update anything with apt now it says that my dkms package isn't configuring and I assume this is the problem. This issue just popped up a few days ago I had solved the configure issue for my self a while ago but it seems to be back again.
