### ISSUE TITLE
Wifi spontanously going off 

### ISSUE THREAD

**Issue by WWBKx** [linux-surface/linux-surface#222]
[Description of the bug or feature]

Wifi spontanously goes of on my ubuntu 20.04 lts version. Somehow after a reboot everything is okay, but after a while it just shuts down.

```
$ cat /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf 
[connection]
wifi.powersave = 2


$ cat /etc/NetworkManager/conf.d/99-surface.conf 
[connection]
wifi.powersave = 2

[device]
wifi.scan-rand-mac-address=false
```
Somehow it also appears that the whole adapter doesnt seem to be listed anymore. Cant acces it through network manager nor through connecting to it.

Tried also redoing the setup.sh but it doenst take a way the problem. 

Any tips?

### Environment

- Hardware model:  Surface Laptop (1st Gen)
- Kernel version:  Linux "hostname" 5.7.5-surface #1 SMP Wed Jun 24 15:46:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Distribution:  Ubuntu

<details><summary>`dmesg` output</summary>

```
please provide a copy of `dmesg` here if possible

[    5.202645] mwifiex_pcie 0000:02:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.19.p21) 
[    5.202647] mwifiex_pcie 0000:02:00.0: driver_version = mwifiex 1.0 (15.68.19.p21) 
[    5.849721] mwifiex_pcie 0000:02:00.0 wlp2s0: renamed from mlan0
[    5.986736] Bluetooth: Core ver 2.22
[    5.986753] NET: Registered protocol family 31
[    5.986754] Bluetooth: HCI device and connection manager initialized
[    5.986758] Bluetooth: HCI socket layer initialized
[    5.986760] Bluetooth: L2CAP socket layer initialized
[    5.986762] Bluetooth: SCO socket layer initialized
[    6.011137] vboxdrv: loading out-of-tree module taints kernel.
[    6.011391] vboxdrv: module verification failed: signature and/or required key missing - tainting kernel
[    6.022705] vboxdrv: Found 4 processor cores
[    6.030784] usbcore: registered new interface driver btusb
[    6.032518] Bluetooth: hci0: unexpected event for opcode 0x0000
[    6.035190] Bluetooth: hci0: unexpected event for opcode 0x0000
[    6.041663] vboxdrv: TSC mode is Invariant, tentative frequency 2712003422 Hz
[    6.041664] vboxdrv: Successfully loaded version 6.1.6_Ubuntu (interface 0x002d0001)
[    6.054731] VBoxNetFlt: Successfully started.
[    6.064778] VBoxNetAdp: Successfully started.
[    6.161870] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[    6.161871] Bluetooth: BNEP filters: protocol multicast
[    6.161876] Bluetooth: BNEP socket layer initialized
[    6.223259] NET: Registered protocol family 38
[    7.793775] Bluetooth: RFCOMM TTY layer initialized
[    7.793780] Bluetooth: RFCOMM socket layer initialized
[    7.793785] Bluetooth: RFCOMM ver 1.11
[   16.470607] rfkill: input handler disabled
[   35.236552] mwifiex_pcie 0000:02:00.0: Request to enable ps_mode received but it's disallowed by module parameter. Rejecting the request.
[   39.600251] mwifiex_pcie 0000:02:00.0: info: trying to associate to 'WIFINETWORK' bssid 28:ff:3e:21:0d:4c
[   39.698940] mwifiex_pcie 0000:02:00.0: info: associated to bssid 28:ff:3e:21:0d:4c successfully
[   39.711220] IPv6: ADDRCONF(NETDEV_CHANGE): wlp2s0: link becomes ready
[   48.063934] kauditd_printk_skb: 33 callbacks suppressed
[   48.063935] audit: type=1400 audit(1593417598.970:44): apparmor="DENIED" operation="capable" profile="/snap/snapd/8140/usr/lib/snapd/snap-confine" pid=1904 comm="snap-confine" capability=4  capname="fsetid"
[  527.260940] VirtualBox[3278]: segfault at 10 ip 0000562e4591f077 sp 00007ffc8b075b40 error 4 in VirtualBox[562e458d7000+199000]
[  527.260948] Code: 00 00 00 31 c0 e8 59 6f 00 00 48 89 c5 48 85 c0 0f 84 75 02 00 00 44 0f b6 78 14 45 89 fe 48 8b 05 d6 dc 1c 00 48 89 44 24 20 <8b> 45 10 85 c0 0f 85 ae 01 00 00 4c 8d 44 24 20 4c 8d 64 24 28 48
[  986.309409] SUPR0GipMap: fGetGipCpu=0x1b
[ 1008.040581] vboxdrv: 0000000000000000 VMMR0.r0
[ 1008.157469] vboxdrv: 0000000000000000 VBoxDDR0.r0
[ 1008.210434] VMMR0InitVM: eflags=246 fKernelFeatures=0x0 (SUPKERNELFEATURES_SMAP=0)
[ 1406.020733] mwifiex_pcie 0000:02:00.0: mwifiex_cmd_timeout_func: Timeout cmd id = 0xa4, act = 0x0
[ 1406.020740] mwifiex_pcie 0000:02:00.0: num_data_h2c_failure = 0
[ 1406.020745] mwifiex_pcie 0000:02:00.0: num_cmd_h2c_failure = 0
[ 1406.020749] mwifiex_pcie 0000:02:00.0: is_cmd_timedout = 1
[ 1406.020753] mwifiex_pcie 0000:02:00.0: num_tx_timeout = 0
[ 1406.020756] mwifiex_pcie 0000:02:00.0: last_cmd_index = 3
[ 1406.020760] mwifiex_pcie 0000:02:00.0: last_cmd_id: a4 00 7f 00 16 00 a4 00 16 00
[ 1406.020763] mwifiex_pcie 0000:02:00.0: last_cmd_act: 00 00 00 00 00 00 00 00 00 00
[ 1406.020766] mwifiex_pcie 0000:02:00.0: last_cmd_resp_index = 2
[ 1406.020769] mwifiex_pcie 0000:02:00.0: last_cmd_resp_id: a4 80 7f 80 16 80 7f 80 16 80
[ 1406.020771] mwifiex_pcie 0000:02:00.0: last_event_index = 1
[ 1406.020774] mwifiex_pcie 0000:02:00.0: last_event: 33 00 1c 00 6a 00 17 00 2b 00
[ 1406.020777] mwifiex_pcie 0000:02:00.0: data_sent=1 cmd_sent=1
[ 1406.020779] mwifiex_pcie 0000:02:00.0: ps_mode=0 ps_state=0
[ 1406.020864] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1406.021427] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1406.021432] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1406.021681] mwifiex_pcie 0000:02:00.0: ===mwifiex driverinfo dump start===
[ 1406.021692] mwifiex_pcie 0000:02:00.0: info: MWIFIEX VERSION: mwifiex 1.0 (15.68.19.p21) 
[ 1406.021711] mwifiex_pcie 0000:02:00.0: PCIE register dump start
[ 1406.021796] mwifiex_pcie 0000:02:00.0: pcie scratch register:
[ 1406.021813] mwifiex_pcie 0000:02:00.0: reg:0xcf0, value=0xfedcba00
               reg:0xcf8, value=0xbb4196
               reg:0xcfc, value=0x2b6b600

[ 1406.021819] mwifiex_pcie 0000:02:00.0: PCIE register dump end
[ 1406.021922] mwifiex_pcie 0000:02:00.0: ===mwifiex driverinfo dump end===
[ 1406.021929] mwifiex_pcie 0000:02:00.0: == mwifiex firmware dump start ==
[ 1406.021953] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1406.021957] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1406.022049] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1406.022053] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1412.006397] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1412.006401] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1412.006469] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1412.006471] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1418.004886] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1418.004889] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1418.004941] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1418.004943] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1424.004865] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1424.004868] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1424.004908] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1424.004910] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1430.004900] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1430.004903] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1430.004943] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1430.004945] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1436.004988] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1436.004993] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1436.005075] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1436.005077] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1442.005889] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1442.005893] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1442.005945] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1442.005946] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1448.002691] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1448.002694] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1448.002742] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1448.002744] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1454.004914] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1454.004918] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1454.004987] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1454.004989] mwifiex_pcie 0000:02:00.0: failed to get signal information
[ 1458.466820] mwifiex_pcie 0000:02:00.0: Firmware dump Finished!
[ 1458.466824] mwifiex_pcie 0000:02:00.0: == mwifiex firmware dump end ==
[ 1458.467255] mwifiex_pcie 0000:02:00.0: == mwifiex dump information to /sys/class/devcoredump start
[ 1458.467365] mwifiex_pcie 0000:02:00.0: == mwifiex dump information to /sys/class/devcoredump end
[ 1458.467373] mwifiex_pcie 0000:02:00.0: PREP_CMD: FW is in bad state
[ 1458.467437] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 1458.467442] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 1458.467446] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 1458.467450] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 1458.467453] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 1458.467456] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 1458.467460] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 1458.467464] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 1458.467468] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 1458.467472] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 1458.467476] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 1458.467480] mwifiex_pcie 0000:02:00.0: deleting the crypto keys
[ 1458.467520] mwifiex_pcie 0000:02:00.0: info: shutdown mwifiex...
[ 1458.467581] mwifiex_pcie 0000:02:00.0: rx_pending=0, tx_pending=1,	cmd_pending=0
[ 1458.470376] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 1458.470385] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 1458.470393] mwifiex_pcie 0000:02:00.0: PREP_CMD: card is removed
[ 1459.622968] mwifiex_pcie 0000:02:00.0: WLAN FW already running! Skip FW dnld
[ 1459.622975] mwifiex_pcie 0000:02:00.0: WLAN FW is active
[ 1469.764880] mwifiex_pcie 0000:02:00.0: mwifiex_cmd_timeout_func: Timeout cmd id = 0xfa, act = 0x4000
[ 1469.764885] mwifiex_pcie 0000:02:00.0: num_data_h2c_failure = 0
[ 1469.764887] mwifiex_pcie 0000:02:00.0: num_cmd_h2c_failure = 0
[ 1469.764889] mwifiex_pcie 0000:02:00.0: is_cmd_timedout = 1
[ 1469.764892] mwifiex_pcie 0000:02:00.0: num_tx_timeout = 0
[ 1469.764894] mwifiex_pcie 0000:02:00.0: last_cmd_index = 4
[ 1469.764896] mwifiex_pcie 0000:02:00.0: last_cmd_id: a4 00 7f 00 16 00 a4 00 fa 00
[ 1469.764899] mwifiex_pcie 0000:02:00.0: last_cmd_act: 00 00 00 00 00 00 00 00 00 40
[ 1469.764901] mwifiex_pcie 0000:02:00.0: last_cmd_resp_index = 2
[ 1469.764904] mwifiex_pcie 0000:02:00.0: last_cmd_resp_id: a4 80 7f 80 16 80 7f 80 16 80
[ 1469.764906] mwifiex_pcie 0000:02:00.0: last_event_index = 1
[ 1469.764908] mwifiex_pcie 0000:02:00.0: last_event: 33 00 1c 00 6a 00 17 00 2b 00
[ 1469.764911] mwifiex_pcie 0000:02:00.0: data_sent=0 cmd_sent=1
[ 1469.764913] mwifiex_pcie 0000:02:00.0: ps_mode=0 ps_state=0
[ 1469.764950] mwifiex_pcie 0000:02:00.0: info: _mwifiex_fw_dpc: unregister device
```

</details>

**Comment by runekaagaard** [comment]
Hi, see https://github.com/linux-surface/linux-surface/issues/70. Turning off bluetooth in the bios should fix the problem.

**Comment by darrabito** [comment]
> Hi, see #70. Turning off bluetooth in the bios should fix the problem. 

I have the same problem that @WWBKx described, and this did not fix it.

**Comment by jonas2515** [comment]
This is the firmware crash that has been fixed by https://github.com/linux-surface/kernel/pull/70, please update to the newest linux-surface kernel and check if the issue persists.

**Comment by jonas2515** [comment]
Closing this, as it should be fixed, please reopen if the issue persists with the newest kernel.
