### ISSUE TITLE
Question: Process of Installation

### ISSUE THREAD

**Issue by WillPower3309** [linux-surface/linux-surface#240]
Hello, I am working on building a [script](https://github.com/WillPower3309/gentoo-linux-surface/blob/master/setup.sh) to patch the Gentoo kernel with the surface changes from the `patches` directory of this repo. After patching and recompiling / reinstalling the kernel, I am noticing that the kernel seems to remain unchanged (note that in addition to the script that patches the kernel source, the user must also compile the new kernel themselves). The battery, touchscreen, and volume buttons on my surface pro 6 seem to still be undetected. Is there a step in the process I'm missing? Any insight is much appreciated:)

**Comment by qzed** [comment]
Based on the script you might be missing the relevant config options (see [`configs/`](https://github.com/linux-surface/linux-surface/tree/master/configs)). You can generate a full config with that and a base config (e.g. one provided by Gentoo) via the `scripts/kconfig/merge_config.sh` script in the kernel source tree.

**Comment by WillPower3309** [comment]
> Based on the script you might be missing the relevant config options (see [`configs/`](https://github.com/linux-surface/linux-surface/tree/master/configs)). You can generate a full config with that and a base config (e.g. one provided by Gentoo) via the `scripts/kconfig/merge_config.sh` script in the kernel source tree.

Exactly what I was looking for, thanks!

**Comment by WillPower3309** [comment]
```
sudo sh /usr/src/linux/scripts/kconfig/merge_config.sh /usr/src/linux/.config ~/Downloads/linux-surface/configs/surface-5.4.config
Using /usr/src/linux/.config as base
Merging /home/will/Downloads/linux-surface/configs/surface-5.4.config
Value of CONFIG_SURFACE_PRO3_BUTTON is redefined by fragment /home/will/Downloads/linux-surface/configs/surface-5.4.config:
Previous value: # CONFIG_SURFACE_PRO3_BUTTON is not set
New value: CONFIG_SURFACE_PRO3_BUTTON=m

make: *** No rule to make target 'alldefconfig'.  Stop.
```
Hey @qzed ! even after merging, upon reboot it still doesnt detect the battery, and the volume buttons still dont work. Sorry to pester but do you think I'm possibly missing anything else

**Comment by StollD** [comment]
The `merge_config.sh` script will try to call `make alldefconfig` to automatically fix dependency issues in the config file. But for that to work, you need to call it from the root of the kernel source tree.

When you dont call it from the kernel tree, you can try adding the `-m` flag which disables the call to `make alldefconfig`.

**Comment by qzed** [comment]
Also check that all options from the Surface config have been set in the final config of the built kernel. If not all dependencies are fulfilled, some options might not get set.

**Comment by WillPower3309** [comment]
Thanks guys! It looks like I'm having issues merging the configs after running the script from the `/usr/src/linux` directory
```
Using .config as base
Merging /home/will/Downloads/linux-surface/configs/surface-5.4.config
Value of CONFIG_SURFACE_SAM is redefined by fragment /home/will/Downloads/linux-surface/configs/surface-5.4.config:
Previous value: CONFIG_SURFACE_SAM=y
New value: CONFIG_SURFACE_SAM=m

Value of CONFIG_TOUCHSCREEN_IPTS is redefined by fragment /home/will/Downloads/linux-surface/configs/surface-5.4.config:
Previous value: CONFIG_TOUCHSCREEN_IPTS=y
New value: CONFIG_TOUCHSCREEN_IPTS=m

Value of CONFIG_SURFACE_3_POWER_OPREGION is redefined by fragment /home/will/Downloads/linux-surface/configs/surface-5.4.config:
Previous value: CONFIG_SURFACE_3_POWER_OPREGION=y
New value: CONFIG_SURFACE_3_POWER_OPREGION=m CONFIG_SURFACE_3_POWER_OPREGION=m

Value of CONFIG_SURFACE_PRO3_BUTTON is redefined by fragment /home/will/Downloads/linux-surface/configs/surface-5.4.config:
Previous value: # CONFIG_SURFACE_PRO3_BUTTON is not set
New value: CONFIG_SURFACE_PRO3_BUTTON=m

scripts/kconfig/conf  --alldefconfig Kconfig
./.tmp.config.gu5h6Um1aN:4281:warning: override: reassigning to symbol SURFACE_3_POWER_OPREGION
#
# configuration written to .config
#
Value requested for CONFIG_GPIO_SYSFS not in final .config
Requested value:  CONFIG_GPIO_SYSFS=y                         # required for SURFACE_SAM_HPS
Actual value:

Value requested for CONFIG_SURFACE_SAM_SSH not in final .config
Requested value:  CONFIG_SURFACE_SAM_SSH=m
Actual value:

Value requested for CONFIG_SURFACE_SAM_SSH_DEBUG_DEVICE not in final .config
Requested value:  CONFIG_SURFACE_SAM_SSH_DEBUG_DEVICE=y
Actual value:

Value requested for CONFIG_SURFACE_SAM_SAN not in final .config
Requested value:  CONFIG_SURFACE_SAM_SAN=m
Actual value:

Value requested for CONFIG_SURFACE_SAM_VHF not in final .config
Requested value:  CONFIG_SURFACE_SAM_VHF=m
Actual value:

Value requested for CONFIG_SURFACE_SAM_DTX not in final .config
Requested value:  CONFIG_SURFACE_SAM_DTX=m
Actual value:

Value requested for CONFIG_SURFACE_SAM_HPS not in final .config
Requested value:  CONFIG_SURFACE_SAM_HPS=m
Actual value:

Value requested for CONFIG_SURFACE_SAM_SID not in final .config
Requested value:  CONFIG_SURFACE_SAM_SID=m
Actual value:

Value requested for CONFIG_SURFACE_SAM_SID_GPELID not in final .config
Requested value:  CONFIG_SURFACE_SAM_SID_GPELID=m
Actual value:

Value requested for CONFIG_SURFACE_SAM_SID_PERFMODE not in final .config
Requested value:  CONFIG_SURFACE_SAM_SID_PERFMODE=m
Actual value:

Value requested for CONFIG_SURFACE_SAM_SID_VHF not in final .config
Requested value:  CONFIG_SURFACE_SAM_SID_VHF=m
Actual value:

Value requested for CONFIG_SURFACE_SAM_SID_POWER not in final .config
Requested value:  CONFIG_SURFACE_SAM_SID_POWER=m
Actual value:

Value requested for CONFIG_INPUT_SOC_BUTTON_ARRAY not in final .config
Requested value:  CONFIG_INPUT_SOC_BUTTON_ARRAY=m
Actual value:

Value requested for CONFIG_SURFACE_3_POWER_OPREGION not in final .config
Requested value:  CONFIG_SURFACE_3_POWER_OPREGION=m
CONFIG_SURFACE_3_POWER_OPREGION=m
Actual value:     CONFIG_SURFACE_3_POWER_OPREGION=m

Value requested for CONFIG_SURFACE_3_BUTTON not in final .config
Requested value:  CONFIG_SURFACE_3_BUTTON=m
Actual value:

Value requested for CONFIG_SURFACE_3_POWER_OPREGION not in final .config
Requested value:  CONFIG_SURFACE_3_POWER_OPREGION=m
CONFIG_SURFACE_3_POWER_OPREGION=m
Actual value:     CONFIG_SURFACE_3_POWER_OPREGION=m
```

**Comment by qzed** [comment]
Hmm, do you have the patches applied while running the script? I think it's either that or missing dependencies for those options.

If it's a dependency issue, the necessary dependencies for those options can be found in the Kconfig files (e.g. https://github.com/linux-surface/kernel/blob/551b70e29582e2ccd1ec255ebdd464f090f00e1b/drivers/platform/x86/surface_sam/Kconfig#L18). `CONFIG_SURFACE_SAM_SSH` not being set basically blocks all other `CONFIG_SURFACE_SAM_xxx` options. That in turn depends on [`CONFIG_SERIAL_DEV_CTRL_TTYPORT`](https://elixir.bootlin.com/linux/v5.7.8/source/drivers/tty/serdev/Kconfig#L14), which depends on [`CONFIG_SERIAL_DEV_BUS=y`](https://elixir.bootlin.com/linux/v5.7.8/source/drivers/tty/serdev/Kconfig#L5).

Its probably easiest if you use a config of one of the larger distributions as base (e.g. Ubuntu, Arch, Fedora, ...), those are configured to have a wide range of device support. Looking at [this](https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-kernel/gentoo-kernel/gentoo-kernel-5.7.10.ebuild) ebuild, the standard Gentoo kernels seem to go with a [Fedora config](https://src.fedoraproject.org/rpms/kernel/raw/14d239184a721485a823f30f5aede1c6190558ad/f/kernel-x86_64-fedora.config). The builtin `make alldefconfig` of the kernel is pretty minimal and not really suited for normal desktop builds (it's pretty much intended as base config for the current architecture, IIRC).

**Comment by WillPower3309** [comment]
Thanks man! Appreciate the help

**Comment by WillPower3309** [comment]
I was able to get the config working properly, I had missed those dependencies, and also the GPIO device drivers, which I corrected. It seems like im having a new issue with make `modules_install`:

```
sudo make modules_install
  INSTALL drivers/input/touchscreen/ipts/ipts.ko
  INSTALL drivers/misc/mei/mei.ko
  INSTALL drivers/net/wireless/marvell/mwifiex/mwifiex.ko
  INSTALL drivers/net/wireless/marvell/mwifiex/mwifiex_pcie.ko
  INSTALL drivers/platform/x86/surface3_power.ko
cp: cannot stat 'drivers/input/touchscreen/ipts/ipts.ko': No such file or directory
make[1]: *** [scripts/Makefile.modinst:33: drivers/input/touchscreen/ipts/ipts.ko] Error 1
make[1]: *** Waiting for unfinished jobs....
cp: cannot stat 'drivers/misc/mei/mei.ko': No such file or directory
make[1]: *** [scripts/Makefile.modinst:33: drivers/misc/mei/mei.ko] Error 1
make: *** [Makefile:1331: _modinst_] Error 2
```

**Comment by WillPower3309** [comment]
After observing the kernel input drivers directory I am noticing `ipts.mod`, `ipts.mod.c`, and `ipts.o`, but no `ipts.ko`

**Comment by qzed** [comment]
Hmm, that's odd. `mei.ko` also seems to be missing. Are you sure the previous build did not run into any error? You do have `CONFIG_INTEL_MEI`, `INTEL_MEI_ME`, and `CONFIG_TOUCHSCREEN_IPTS` set to `m`, right?

**Comment by WillPower3309** [comment]
Decided to take a break from this and come back to it, discovered a build error:
```
drivers/misc/surface_sam/ssh_request_layer.c:38:1: warning: data definition has no type or storage class
   38 | ALLOW_ERROR_INJECTION(ssh_rtl_should_drop_response, TRUE);
      | ^~~~~~~~~~~~~~~~~~~~~
drivers/misc/surface_sam/ssh_request_layer.c:38:1: error: type defaults to ‘int’ in declaration of ‘ALLOW_ERROR_INJECTION’ [-Werror=implicit-int]
drivers/misc/surface_sam/ssh_request_layer.c:38:1: warning: parameter names (without types) in function declaration
  CC      drivers/gpu/drm/i915/gt/uc/intel_huc_fw.o
drivers/misc/surface_sam/ssh_packet_layer.c:198:1: warning: data definition has no type or storage class
  198 | ALLOW_ERROR_INJECTION(ssh_ptl_should_drop_ack_packet, TRUE);
      | ^~~~~~~~~~~~~~~~~~~~~
drivers/misc/surface_sam/ssh_packet_layer.c:198:1: error: type defaults to ‘int’ in declaration of ‘ALLOW_ERROR_INJECTION’ [-Werror=implicit-int]
drivers/misc/surface_sam/ssh_packet_layer.c:198:1: warning: parameter names (without types) in function declaration
drivers/misc/surface_sam/ssh_packet_layer.c:211:1: warning: data definition has no type or storage class
  211 | ALLOW_ERROR_INJECTION(ssh_ptl_should_drop_nak_packet, TRUE);
      | ^~~~~~~~~~~~~~~~~~~~~
drivers/misc/surface_sam/ssh_packet_layer.c:211:1: error: type defaults to ‘int’ in declaration of ‘ALLOW_ERROR_INJECTION’ [-Werror=implicit-int]
drivers/misc/surface_sam/ssh_packet_layer.c:211:1: warning: parameter names (without types) in function declaration
drivers/misc/surface_sam/ssh_packet_layer.c:225:1: warning: data definition has no type or storage class
  225 | ALLOW_ERROR_INJECTION(ssh_ptl_should_drop_dsq_packet, TRUE);
      | ^~~~~~~~~~~~~~~~~~~~~
drivers/misc/surface_sam/ssh_packet_layer.c:225:1: error: type defaults to ‘int’ in declaration of ‘ALLOW_ERROR_INJECTION’ [-Werror=implicit-int]
drivers/misc/surface_sam/ssh_packet_layer.c:225:1: warning: parameter names (without types) in function declaration
drivers/misc/surface_sam/ssh_packet_layer.c:237:1: warning: data definition has no type or storage class
  237 | ALLOW_ERROR_INJECTION(ssh_ptl_should_fail_write, ERRNO);
      | ^~~~~~~~~~~~~~~~~~~~~
drivers/misc/surface_sam/ssh_packet_layer.c:237:1: error: type defaults to ‘int’ in declaration of ‘ALLOW_ERROR_INJECTION’ [-Werror=implicit-int]
drivers/misc/surface_sam/ssh_packet_layer.c:237:1: warning: parameter names (without types) in function declaration
drivers/misc/surface_sam/ssh_packet_layer.c:253:1: warning: data definition has no type or storage class
  253 | ALLOW_ERROR_INJECTION(ssh_ptl_should_corrupt_tx_data, TRUE);
      | ^~~~~~~~~~~~~~~~~~~~~
drivers/misc/surface_sam/ssh_packet_layer.c:253:1: error: type defaults to ‘int’ in declaration of ‘ALLOW_ERROR_INJECTION’ [-Werror=implicit-int]
drivers/misc/surface_sam/ssh_packet_layer.c:253:1: warning: parameter names (without types) in function declaration
drivers/misc/surface_sam/ssh_packet_layer.c:266:1: warning: data definition has no type or storage class
  266 | ALLOW_ERROR_INJECTION(ssh_ptl_should_corrupt_rx_syn, TRUE);
      | ^~~~~~~~~~~~~~~~~~~~~
drivers/misc/surface_sam/ssh_packet_layer.c:266:1: error: type defaults to ‘int’ in declaration of ‘ALLOW_ERROR_INJECTION’ [-Werror=implicit-int]
drivers/misc/surface_sam/ssh_packet_layer.c:266:1: warning: parameter names (without types) in function declaration
drivers/misc/surface_sam/ssh_packet_layer.c:279:1: warning: data definition has no type or storage class
  279 | ALLOW_ERROR_INJECTION(ssh_ptl_should_corrupt_rx_data, TRUE);
      | ^~~~~~~~~~~~~~~~~~~~~
drivers/misc/surface_sam/ssh_packet_layer.c:279:1: error: type defaults to ‘int’ in declaration of ‘ALLOW_ERROR_INJECTION’ [-Werror=implicit-int]
drivers/misc/surface_sam/ssh_packet_layer.c:279:1: warning: parameter names (without types) in function declaration
  CC [M]  drivers/net/wireless/marvell/mwifiex/wmm.o
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:266: drivers/misc/surface_sam/ssh_request_layer.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  CC [M]  drivers/net/wireless/marvell/mwifiex/11n.o
  CC      drivers/pci/irq.o
  CC      drivers/pci/vpd.o
  CC      drivers/gpu/drm/i915/display/intel_atomic.o
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:265: drivers/misc/surface_sam/ssh_packet_layer.o] Error 1
make[2]: *** [scripts/Makefile.build:500: drivers/misc/surface_sam] Error 2
make[1]: *** [scripts/Makefile.build:500: drivers/misc] Error 2
make[1]: *** Waiting for unfinished jobs....
```

and then later:
`make: *** [Makefile:1706: drivers] Error 2`

**Comment by qzed** [comment]
Oh, hmm, I might have messed some includes up there... I'l try to figure this out later.

You should be able to avoid those errors by setting `CONFIG_SURFACE_SAM_SSH_ERROR_INJECTION=n`, which is probably what you want anyways. The error injection part is only useful for debugging, basically as the name implies to deliberately inject errors into the SAM/SSH communication. It's not something that you need, unless you want to debug and test the module.

**Comment by qzed** [comment]
The include issue should be fixed with the latest patches.

**Comment by WillPower3309** [comment]
> The include issue should be fixed with the latest patches.

Ton of respect for all the help, thanks!

I've successfully compiled and installed the kernel & modules, yet the device buttons / battery is still not working (i expect the touchscreen to require more dependencies), would this be caused by a lack of initramfs? I hadn't needed to create one prior to this

**Comment by qzed** [comment]
An initram is only required for early loading of certain drivers built as modules (and firmware). AFAIK usually file-system drivers, but could also be stuff that's required for decrypting an encrypted root partition. So that shouldn't be the issue.

Can you check if the built kernel contains the required modules? E.g. `modinfo surface_sam_ssh` should find the module. If that isn't there, then it's probably a config issue again (make sure they are all up-to-date, as found in the `configs/` directory).

**Comment by WillPower3309** [comment]
Can confirm that the modules appear via modinfo and appear in the proper `/lib` directory

**Comment by qzed** [comment]
Okay, anything in dmesg? Normally the modules should auto-load, so maybe there's an error when probing the driver.

**Comment by WillPower3309** [comment]
dmesg appears to be fine, no messages relating to surface_sam whatsoever, only error is related to i915 direct firmware loading, it should detect the battery with no further tinkering right?

**Comment by qzed** [comment]
You should see a line like `surface_sam_ssh serial0-0: SAM controller version: <version>` when the Serial Hub (core) driver loads. Can you upload the output of `lsmod` and try running `modprobe surface_sam_ssh`?

**Comment by WillPower3309** [comment]
```
> lsmod
Module                  Size  Used by
mwifiex_pcie           40960  0
surface_gpe            20480  0
mwifiex               294912  1 mwifiex_pcie
x86_pkg_temp_thermal    20480  0
surface_sam_san        16384  0
surface_sam_device_hub    16384  0
surface_sam_ssh        98304  2 surface_sam_device_hub,surface_sam_san
surfacepro3_button     16384  0
efivarfs               16384  1
```

`modprobe surface_sam_ssh` returned empty

**Comment by qzed** [comment]
Okay, so the modules are loaded. Can you check that the drivers are bound? To do that run
```
ls -l /sys/bus/platform/devices/<device>/
```
and replace ´<device>` with `MSHW0084:00` for SSH and `MSHW0091:00` for SAN. You should see a `driver` symlink in both.

**Comment by qzed** [comment]
Regarding buttons: I can't see the `soc_button_array` module. Is that compiled in or is that not compiled at all (check for `CONFIG_INPUT_SOC_BUTTON_ARRAY` in the config)?

**Comment by WillPower3309** [comment]
> Regarding buttons: I can't see the `soc_button_array` module in lsmod. Is that compiled in or is that not compiled at all (check for `CONFIG_INPUT_SOC_BUTTON_ARRAY` in the config)?

Compiled in! Should I add it as a module?

**Comment by WillPower3309** [comment]
And it appears that `/sys/bus/serial/devices` is empty. 

```
> ls -l /sys/bus/platform/devices/MSHW0091:00/
total 0
-rw-r--r-- 1 root root 4096 Aug 29 20:19 driver_override
lrwxrwxrwx 1 root root    0 Aug 29 20:19 firmware_node -> ../../LNXSYSTM:00/LNXSYBUS:00/MSHW0091:00
-r--r--r-- 1 root root 4096 Aug 29 20:19 modalias
drwxr-xr-x 2 root root    0 Aug 29 20:19 power
lrwxrwxrwx 1 root root    0 Aug 29 20:18 subsystem -> ../../../bus/platform
-rw-r--r-- 1 root root 40> ls -l /sys/bus/platform/devices/MSHW0091:00/
total 0
-rw-r--r-- 1 root root 4096 Aug 29 20:19 driver_override
lrwxrwxrwx 1 root root    0 Aug 29 20:19 firmware_node -> ../../LNXSYSTM:00/LNXSYBUS:00/MSHW0091:00
-r--r--r-- 1 root root 4096 Aug 29 20:19 modalias
drwxr-xr-x 2 root root    0 Aug 29 20:19 power
lrwxrwxrwx 1 root root    0 Aug 29 20:18 subsystem -> ../../../bus/platform
-rw-r--r-- 1 root root 4096 Aug 29 20:18 uevent96 Aug 29 20:18 uevent
```

**Comment by qzed** [comment]
> 
> 
> > Regarding buttons: I can't see the `soc_button_array` module in lsmod. Is that compiled in or is that not compiled at all (check for `CONFIG_INPUT_SOC_BUTTON_ARRAY` in the config)?
> 
> Compiled in! Should I add it as a module?

Should work either way. You can check if there's a driver bound to `/sys/bus/platform/devices/MSHW0040:00/`.


> And it appears that `/sys/bus/serial/devices` is empty.

So the serial device is missing. That means either it's a config issue or you're missing a patch (only on 5.4 and older kernels). I assume that you've applied the correct patches for your kernel version from the patches directory, so we can rule the last one out.

The serial device depends on a couple of options, most of them depending on the actual hardware. I assume you already have `CONFIG_SERIAL_DEV_CTRL_TTYPORT=y` and `CONFIG_SERIAL_DEV_BUS=y` which we discussed before. Those are for the serdev subsystem. I think what might be missing here is the actual driver for the serial device. As far as I remember that's a dw8520 on the Intel models, so I think you'll need at least
```
CONFIG_SERIAL_8250=y
CONFIG_SERIAL_8250_DW=y
CONFIG_SERIAL_8250_DMA=y
```
and possibly more. Here's what Fedora has set for the `SERIAL_8250` options:
```
# CONFIG_SERIAL_8250_16550A_VARIANTS is not set
# CONFIG_SERIAL_8250_ASPEED_VUART is not set
CONFIG_SERIAL_8250_CONSOLE=y
CONFIG_SERIAL_8250_CS=m
# CONFIG_SERIAL_8250_DEPRECATED_OPTIONS is not set
# CONFIG_SERIAL_8250_DETECT_IRQ is not set
CONFIG_SERIAL_8250_DW=y
CONFIG_SERIAL_8250_EXAR=m
CONFIG_SERIAL_8250_EXTENDED=y
# CONFIG_SERIAL_8250_FINTEK is not set
CONFIG_SERIAL_8250_LPSS=m
CONFIG_SERIAL_8250_MANY_PORTS=y
CONFIG_SERIAL_8250_MID=y
CONFIG_SERIAL_8250_NR_UARTS=32
CONFIG_SERIAL_8250_PCI=y
CONFIG_SERIAL_8250_RSA=y
CONFIG_SERIAL_8250_RT288X=y
CONFIG_SERIAL_8250_RUNTIME_UARTS=32
CONFIG_SERIAL_8250_SHARE_IRQ=y
CONFIG_SERIAL_8250=y
```
Furthermore, that device is actually provided via an the Intel LPSS PCIe device, so you'll also need
```
CONFIG_X86_INTEL_LPSS=y
CONFIG_MFD_INTEL_LPSS_ACPI=y
CONFIG_MFD_INTEL_LPSS_PCI=y
```

Again, not sure if that is everything you need. Also make sure to check that they are properly enabled and not dropped due to missing dependencies.

**Comment by WillPower3309** [comment]
I applied those options and also applied the fedora PINCTRL options and now I have battery showing! The volume buttons still arent working (and i still need to test touchscreen after installing the related packages), but there is now also a symlink in `/sys/bus/serial/devices/serial0-0`!

```
> ls -l /sys/bus/serial/devices/serial0-0
lrwxrwxrwx 1 root root 0 Aug 30 07:37 /sys/bus/serial/devices/serial0-0 -> ../../../devices/pci0000:00/0000:00:1e.0/dw-apb-uart.4/serial0/serial0-0
```

**Comment by qzed** [comment]
Okay, great! So that means that the SAM modules are working and everything required for at least the base ones is there.

I've got a suspicion regarding the buttons: Could be that, since you compiled the `soc_button_array` module into the kernel, the GPIOs aren't ready yet. If I remember correctly, this has been an issue before.

First, can you check if a driver has been attached to `MSHW0040:00` (run `ls -l /sys/bus/platform/MSHW0040:00` and check for the `driver` symlink)? If there is none (what I assume), can you try running `echo MSHW0040:00 | sudo tee /sys/bus/platform/drivers/soc_button_array/bind` and see if that results in any kernel log messages or fails? If it succeeds, can you check if the buttons work?

**Comment by WillPower3309** [comment]
> Okay, great! So that means that the SAM modules are working and everything required for at least the base ones is there.
> 
> I've got a suspicion regarding the buttons: Could be that, since you compiled the `soc_button_array` module into the kernel, the GPIOs aren't ready yet. If I remember correctly, this has been an issue before.
> 
> First, can you check if a driver has been attached to `MSHW0040:00` (run `ls -l /sys/bus/platform/MSHW0040:00` and check for the `driver` symlink)? If there is none (what I assume), can you try running `echo MSHW0040:00 | sudo tee /sys/bus/platform/drivers/soc_button_array/bind` and see if that results in any kernel log messages or fails (this call requests that the driver should be probed against the device, something that normally happens automatically)? If it succeeds, can you check that the device now has a link to the driver and that the buttons work?

Wow it worked! Thanks a ton, I believe my surface is now 100% working with Gentoo! (or at least will be once I compile the patched wacom drivers)

Really appreciate the time you spent helping me

**Comment by qzed** [comment]
Awesome! I may look into the GPIO setup issue for the `soc_button_array` driver at some point, but no clue when I get to that. In the mean-time I'd recommend compiling any pinctrl/GPIO modules into the kernel (`y`) and keeping the `soc_button_array` as module (`m`). That way the GPIOs should be set up before the button driver loads.

**Comment by WillPower3309** [comment]
Awesome, thanks for the advice! Even with compiling with `soc_button_array` as a module I still need to run `echo MSHW0040:00 | sudo tee /sys/bus/platform/drivers/soc_button_array/bind` before it works

**Comment by qzed** [comment]
Hmm okay, that's a bit odd. If you want to you can try debugging where exactly the problem is by inserting print statements. Specifically at any point that returns `-ENODEV`.

**Comment by WillPower3309** [comment]
@qzed hey! Things are going well, but I'm hoping to get the touchscreen working and I'm having difficulties. My understanding is with IPTS=m, my stylus should work since I am running the 5.4.60 kernel, however that is not the case. Is there any extra configuration that needs to be done on my end?

**Comment by qzed** [comment]
Looks like you're missing `CONFIG_INTEL_MEI_ME=m`.
